### ISSUE TITLE
Volunteers should still have their vacation time displayed

### ISSUE THREAD

**Issue by thisfinalcode** [lzhengem/Java111b_Assignment7_Polymorphism#2]
Norm is a volunteer, but still has his vacation time printed out:
This is the display from the professor:
Name: Norm
Address: 987 Suds Blvd.
Phone: 555-8374
Thanks!
Vacation days available: 0
-----------------------------------

This is the current output:
Name: Norm
Address: 987 Suds Blvd.
Phone: 555-8374
Thanks!
-----------------------------------

**Comment by Nickles255** [comment]
Done! Removed if statement in Staff.java to allow output of Vacation Days.

![image](https://user-images.githubusercontent.com/4764414/33019666-2dab388c-cdb0-11e7-8682-af6485b39e09.png)
