### ISSUE TITLE
Executive sam has 26 vs 24 vacation days

### ISSUE THREAD

**Issue by thisfinalcode** [lzhengem/Java111b_Assignment7_Polymorphism#3]
In her output it looks like her executive sam gets more vacation days than our sam:

Her output
-----------------------------------
Name: Sam
Address: 123 Main Line
Phone: 555-0469
Social Security Number: 123-45-6789
Paid: 2923.07
Vacation days available: 26
-----------------------------------

our output:
-----------------------------------
Name: Sam
Address: 123 Main Line
Phone: 555-0469
Social Security Number: 123-45-6789
Paid: 2923.07
Vacation Days: 24
-----------------------------------

should we match her executive's vacation days?

**Comment by Nickles255** [comment]
I just added 10 days. I think it is to just show the constructor works. Can
change if you want but I don't think it will impact our grade.

**Comment by thisfinalcode** [comment]
Ok, it's been updated. The files have been zipped and uploaded to github.

Best,
Lena

<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virus-free.
www.avg.com
<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>
